# Interpolation for filling missing values

In [4]:
# interpolation is a technique in pythonwith whih you can estimate unknown data points between two data points

In [ ]:
import pandas as pd
import numpy as np

In [2]:
a=pd.Series([0,1,np.nan,3,4,5,6,7])

In [3]:
a

0    0.0
1    1.0
2    NaN
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

## Methods of interpolation

In [6]:
##Linear interpolation

In [7]:
a.interpolate()

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [8]:
##Polynomial Interpolation

In [18]:
a.interpolate(method="polynomial", order=2)

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

# Interpolation in Datframe

In [15]:
s = pd.DataFrame([0.0,np.nan,-2.0,2.0])

In [16]:
s

0
0  0.0
1  NaN
2 -2.0
3  2.0

In [17]:
s.interpolate()

0
0  0.0
1 -1.0
2 -2.0
3  2.0

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [9]:
x=np.array([2,7,9,14,15,12,7])

In [10]:
x

array([ 2,  7,  9, 14, 15, 12,  7])

In [7]:
x[0:4:3]

array([ 2, 14])

In [8]:
x[0:7:3]

array([ 2, 14,  7])

In [14]:
x[0:8:3]

array([ 2, 14,  7])

In [15]:
y=np.array([[3,4],[9,2],[-3,5]])

In [16]:
y

array([[ 3,  4],
       [ 9,  2],
       [-3,  5]])

In [17]:
y[:2:]

array([[3, 4],
       [9, 2]])

In [18]:
z=np.array([[3,2,1],[4,1,7],[1,1,-3],[7,7,-2]])

In [19]:
z

array([[ 3,  2,  1],
       [ 4,  1,  7],
       [ 1,  1, -3],
       [ 7,  7, -2]])

In [21]:
z[:,0:2]

array([[3, 2],
       [4, 1],
       [1, 1],
       [7, 7]])

In [24]:
w=np.array([3,2,4,9,5,15])

In [25]:
w

array([ 3,  2,  4,  9,  5, 15])

In [26]:
w[[0,2,4,5]]

array([ 3,  4,  5, 15])

In [27]:
m=np.mean(w)

In [28]:
m

6.333333333333333

In [29]:
w>m

array([False, False, False,  True, False,  True])

In [30]:
result=w>m

In [31]:
w[result]

array([ 9, 15])

## Reshaping

In [32]:
w1=w[1:]

In [33]:
w1

array([ 2,  4,  9,  5, 15])

In [34]:
w1.shape

(5,)

In [35]:
w1.size

5

In [36]:
w1.reshape(3,2)

ValueError: cannot reshape array of size 5 into shape (3,2)

In [37]:
w2=w1[1:]

In [38]:
w2

array([ 4,  9,  5, 15])

In [39]:
w2.reshape(2,2)

array([[ 4,  9],
       [ 5, 15]])